## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Purushendra Singh"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  # github = "https://github.com/caressofsteel/"
  twitter = "https://twitter.com/puru_354"
  email = "purusingh.354@gmail.com"
  # instagram = "https://instagram.com"
  linkedin = "https://www.linkedin.com/in/puru-singh-6a3b0b1b8/"
  # telegram = "https://telegram.org"